
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-org-v1-ip
  failurePolicy: Fail
  name: vip.kb.io
  rules:
  - apiGroups:
    - paas.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - ips
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-paas-org-v1-virtualip
  failurePolicy: Fail
  name: vvirtualip.kb.io
  rules:
  - apiGroups:
    - paas.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualips
  sideEffects: None
