
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: keepalived-allocator-operator-webhook-server-cert
  name: webhook
  namespace: system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: keepalived-allocator-operator-controller-manager
