apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: ""
    service:
      name: vip-allocator-operator-webhook
  name: vip.kb.io