apiVersion: v1
kind: Service
metadata:
  name: invalid-name-exceeds-the-maximum-number-of-letter
spec:
  ports:
  - name: tcp-5000
    port: 5000
    targetPort: 5000
  selector:
    app: invalid-name-exceeds-the-maximum-number-of-letter-app