apiVersion: v1
kind: Service
metadata:
  name: invalid-illegal-ports-service
spec:
  ports:
  - name: tcp-10250
    port: 10250
    targetPort: 10250
  - name: udp-10250
    port: 10250
    targetPort: 10250
    protocol: UDP
  - name: tcp-5000
    port: 5000
    targetPort: 5000
  - name: tcp-111
    port: 111
    targetPort: 111
    protocol: UDP
  selector:
    app: invalid-illegal-ports-app