apiVersion: v1
kind: Service
metadata:
  name: valid-reserved-ip-service
spec:
  ports:
  - name: tcp-5000
    port: 5000
    targetPort: 5000
  selector:
    app: valid-reserved-ip-app
---
apiVersion: v1
kind: Service
metadata:
  name: invalid-reserved-ip-service
spec:
  ports:
  - name: tcp-5000
    port: 5000
    targetPort: 5000
  selector:
    app: invalid-reserved-ip-app