apiVersion: v1
kind: Service
metadata:
  annotations:
    keepalived-operator.redhat-cop.io/keepalivedgroup: namespace/group
  name: valid-keepalived-annotation-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: valid-keepalived-annotation-app