apiVersion: v1
kind: Service
metadata:
  name: valid-multiple-ports-service
spec:
  ports:
  - name: tcp-5000
    port: 5000
    targetPort: 5000
  - name: tcp-5001-to-5000
    port: 5001
    targetPort: 5000
  - name: tcp-5002
    port: 5002
    targetPort: 5002
  - name: udp-5002
    port: 5002
    targetPort: 5002
    protocol: UDP
  - name: udp-5003
    port: 5003
    targetPort: 5003
    protocol: UDP
  selector:
    app: valid-multiple-ports-app