# permissions for end users to edit groupsegmentmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupsegmentmapping-editor-role
rules:
- apiGroups:
  - paas.org
  resources:
  - groupsegmentmappings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.org
  resources:
  - groupsegmentmappings/status
  verbs:
  - get
