# permissions for end users to view groupsegmentmappings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupsegmentmapping-viewer-role
rules:
- apiGroups:
  - paas.org
  resources:
  - groupsegmentmappings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paas.org
  resources:
  - groupsegmentmappings/status
  verbs:
  - get
