# permissions for end users to edit ips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ip-editor-role
rules:
- apiGroups:
  - paas.org
  resources:
  - ips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.org
  resources:
  - ips/status
  verbs:
  - get
