# permissions for end users to view ipgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipgroup-viewer-role
rules:
- apiGroups:
  - paas.org
  resources:
  - ipgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paas.org
  resources:
  - ipgroups/status
  verbs:
  - get
