# permissions for end users to edit ipgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipgroup-editor-role
rules:
- apiGroups:
  - paas.org
  resources:
  - ipgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.org
  resources:
  - ipgroups/status
  verbs:
  - get
