
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - paas.org
  resources:
  - virtualips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paas.org
  resources:
  - virtualips/finalizers
  verbs:
  - update
- apiGroups:
  - paas.org
  resources:
  - virtualips/status
  verbs:
  - get
  - patch
  - update
