# permissions for end users to view virtualips.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualip-viewer-role
rules:
- apiGroups:
  - paas.org
  resources:
  - virtualips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paas.org
  resources:
  - virtualips/status
  verbs:
  - get
