apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: empty.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: GroupSegmentMapping is the Schema for the groupsegmentmappings API
      displayName: Group Segment Mapping
      kind: GroupSegmentMapping
      name: groupsegmentmappings.paas.org
      version: v1
    - description: IP is the Schema for the ips API
      displayName: IP
      kind: IP
      name: ips.paas.org
      version: v1
    - description: VirtualIP is the Schema for the virtualips API
      displayName: Virtual IP
      kind: VirtualIP
      name: virtualips.paas.org
      version: v1
  description: Allocates available IPs for Keepalived operator
  displayName: keepalived-allocator-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - keepalived
  - allocator
  links:
  - name: Empty
    url: https://empty.domain
  maturity: alpha
  provider:
    name: PAAS
  version: 0.0.0
