apiVersion: v1
kind: ServiceAccount
metadata:
  name: keepalived-allocator-operator-sa
  namespace: keepalived-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: keepalived-allocator-operator-aggregate-gsms-view
rules:
- apiGroups:
  - paas.org
  resources:
  - groupsegmentmappings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: keepalived-allocator-operator-aggregate-virtualips-admin-edit
rules:
- apiGroups:
  - paas.org
  resources:
  - virtualips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: keepalived-allocator-operator-aggregate-virtualips-view
rules:
- apiGroups:
  - paas.org
  resources:
  - virtualips
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keepalived-allocator-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: keepalived-allocator-operator-sa
  namespace: keepalived-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: keepalived-allocator-operator-controller-manager
  name: keepalived-allocator-operator-controller-manager-metrics
  namespace: keepalived-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: keepalived-allocator-operator-controller-manager
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: keepalived-allocator-operator-webhook-server-cert
  name: keepalived-allocator-operator-webhook
  namespace: keepalived-operator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: keepalived-allocator-operator-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: keepalived-allocator-operator-controller-manager
  name: keepalived-allocator-operator-controller-manager
  namespace: keepalived-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: keepalived-allocator-operator-controller-manager
  template:
    metadata:
      labels:
        control-plane: keepalived-allocator-operator-controller-manager
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        command:
        - /manager
        env:
        - name: ILLEGAL_PORTS
          value: '[10250, 111]'
        image: docker.io/paasteam324/keepalived-allocator-operator:0.0.6
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsUser: 65532
      serviceAccountName: keepalived-allocator-operator-sa
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: keepalived-allocator-operator-webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  name: keepalived-allocator-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: keepalived-allocator-operator-webhook
      namespace: keepalived-operator
      path: /validate-paas-org-v1-ip
  failurePolicy: Fail
  name: vip.kb.io
  rules:
  - apiGroups:
    - paas.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - ips
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: keepalived-allocator-operator-webhook
      namespace: keepalived-operator
      path: /validate-paas-org-v1-virtualip
  failurePolicy: Fail
  name: vvirtualip.kb.io
  rules:
  - apiGroups:
    - paas.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - virtualips
  sideEffects: None
